version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - export AWS_DEFAULT_REGION=ap-south-1
      - export ECR_REGISTRY=665059252862.dkr.ecr.ap-south-1.amazonaws.com
      - export ECR_REPO_NAME=traceble-bckend
      - export ECR_REPO_URI=$ECR_REGISTRY/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "Cleaning up existing images..."
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region ap-south-1       
      - AWS_REGION=ap-south-1
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)      
      - IMAGE_TAG=$COMMIT_HASH
      - echo "Copying env.sh and generating .env file..."
      - cp env.sh /usr/local/bin
      - chmod +x /usr/local/bin/env.sh
      - /usr/local/bin/env.sh      
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - printf '{"Parameters":{"ImageUrl":"%s"}}' $ECR_REPO_URI:$IMAGE_TAG > imageuri.json

artifacts:
  files: 
    - ./service.yml
    - imageuri.json  
  
  discard-paths: yes
