name: Deploy to AlmaLinux EC2

on:
  push:
    branches:
      - staging1  

jobs:
  Deploy:
    name: Deploy to EC2 (AlmaLinux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH for Deployment
        run: |
          # Ensure the .ssh directory exists for the current user
          mkdir -p ~/.ssh

          # Remove any old keys for the hostname (if exists)
          ssh-keygen -R ${{ secrets.SSH_HOST }}

          # Add EC2 server to known hosts (to prevent prompt)
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          # Debug: Verify known_hosts file has the right key
          cat ~/.ssh/known_hosts || echo "known_hosts file not found or empty"

          # Add the private key to SSH agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Backend Directory
        env:
          HOSTNAME: ${{ secrets.SSH_HOST }}         
          USER_NAME: ${{ secrets.EC2_USER }}        
        run: |
          # Try key-based SSH authentication
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
              # Navigate to the correct backend directory
              cd /home/ubuntu/tracebalebackend-staging &&

              # Configure Git to use SSH instead of HTTPS
              git config --global url."git@github.com:".insteadOf "https://github.com/" &&

              # Fetch the latest code from the staging1 branch
              git fetch --all &&
              git reset --hard origin/staging1 &&
              git pull origin staging1 &&

              # Install dependencies
              npm install --legacy-peer-deps && 

              # Set execute permission for tsc
              chmod +x ./node_modules/.bin/tsc &&

              # Build the project
              npm run build &&

              # Kill any process using port 5000 and delete the backend PM2 process
              sudo lsof -t -i:5000 | xargs kill -9 &&
              pm2 delete backend &&

              # Start the backend using PM2
              pm2 start npm --name "backend" -- start
          ' || {

            # Fallback to password-based SSH authentication if key-based fails
            echo "Key-based authentication failed. Trying password authentication..." &&

            sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
              # Navigate to the correct backend directory
              cd /home/ubuntu/tracebalebackend-staging &&

              # Configure Git to use SSH instead of HTTPS
              git config --global url."git@github.com:".insteadOf "https://github.com/" &&

              # Fetch the latest code from the staging1 branch
              git fetch --all &&
              git reset --hard origin/staging1 &&
              git pull origin staging1 &&

              # Install dependencies
              npm install --legacy-peer-deps && 

              # Set execute permission for tsc
              chmod +x ./node_modules/.bin/tsc &&

              # Build the project
              npm run build &&

              # Kill any process using port 5000 and delete the backend PM2 process
              sudo lsof -t -i:5000 | xargs kill -9 &&
              pm2 delete backend &&

              # Start the backend using PM2
              pm2 start npm --name "backend" -- start
            '
          }
