name: Deploy to AlmaLinux EC2 staging1

on:
  push:
    branches:
      - staging1 

jobs:
  Deploy:
    name: Deploy to EC2 (AlmaLinux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH for Deployment
        run: |
          # Ensure the .ssh directory exists and set permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Reset the known_hosts file and scan the server key
          echo "" > ~/.ssh/known_hosts
          ssh-keyscan -H 52.66.31.248 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Output known_hosts to verify the correct key is stored
          cat ~/.ssh/known_hosts

          # Setup the private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Backend Directory
        env:
          HOSTNAME: 52.66.31.248
          USER_NAME: ubuntu
        run: |
          # Try key-based SSH authentication
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
              # Navigate to the backend directory
              cd /home/ubuntu/tracebalebackend-staging &&

              # Configure Git to use SSH instead of HTTPS
              git config --global url."git@github.com:".insteadOf "https://github.com/" &&

              # Synchronize the latest source
              git fetch --all &&
              git reset --hard origin/staging1 &&
              git pull origin staging1 &&

              # Install dependencies and prepare the application
              npm install --legacy-peer-deps && 
              chmod +x ./node_modules/.bin/tsc &&
              npm run build &&

              # Clean up any existing process and start fresh
              sudo lsof -t -i:5000 | xargs kill -9
              pm2 delete backend
              pm2 start npm --name "backend" -- start
          '
          
