name: Deploy to AlmaLinux EC2

on:
  push:
    branches:
      - staging1  

jobs:
  Deploy:
    name: Deploy to EC2 (AlmaLinux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH for Deployment
        run: |
          # Create .ssh directory with appropriate permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Clear existing known_hosts and rescan the server to prevent SSH issues
          echo "" > ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Output the contents of known_hosts to check if key was added correctly
          cat ~/.ssh/known_hosts

          # Set up SSH key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Backend Directory
        env:
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          # Establish SSH connection and run deployment commands
          ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
              # Navigate to the correct backend directory
              cd /home/ubuntu/tracebalebackend-staging &&

              # Ensure git is configured to use SSH
              git config --global url."git@github.com:".insteadOf "https://github.com/"

              # Sync repository
              git fetch --all &&
              git reset --hard origin/staging1 &&
              git pull origin staging1 &&

              # Install dependencies and build the project
              npm install --legacy-peer-deps && 
              chmod +x ./node_modules/.bin/tsc &&
              npm run build &&

              # Manage running process
              sudo lsof -t -i:5000 | xargs kill -9 &&
              pm2 delete backend &&
              pm2 start npm --name "backend" -- start
          ' || {
            # Fallback for password-based authentication
            echo "Key-based authentication failed. Trying password authentication..." &&
            sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} '
              cd /home/ubuntu/tracebalebackend-staging &&
              git config --global url."git@github.com:".insteadOf "https://github.com/" &&
              git fetch --all &&
              git reset --hard origin/staging1 &&
              git pull origin staging1 &&
              npm install --legacy-peer-deps &&
              chmod +x ./node_modules/.bin/tsc &&
              npm run build &&
              sudo lsof -t -i:5000 | xargs kill -9 &&
              pm2 delete backend &&
              pm2 start npm --name "backend" -- start
            '
          }
