
name: Sync Repositories

on:
  push:
    branches:
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to destination repository
        run: |
          # Remove any existing destination remote
          git remote remove destination || true
          
          # Add destination repository using the PAT
          git remote add destination "https://${{ secrets.SYNC_TOKEN }}@github.com/vaihainfo/cc--Trace-backend.git"
          
          # Ensure we're on the development branch
          git checkout development
          
          # Force push to destination development branch
          git push destination development:development --force
