
name: Sync Repositories

on:
  push:
    branches:
      - development  # Only trigger on pushes to development branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Push to destination repository
        env:
          SOURCE_BRANCH: development
          DESTINATION_BRANCH: development
          DESTINATION_REPO: "vaihainfo/cc--Trace-backend"
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add destination repository as a remote
          git remote add destination https://${GITHUB_TOKEN}@github.com/${DESTINATION_REPO}.git
          
          # Push to destination repository
          git push destination ${SOURCE_BRANCH}:${DESTINATION_BRANCH} --force
