
name: Sync Repositories

on:
  push:
    branches:
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          fetch-depth: 0

      - name: Sync to Destination Repository
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/vaihainfo/tracebalebackend.git"
          source_branch: "development"
          destination_repo: "https://github.com/vaihainfo/cc--Trace-backend.git"
          destination_branch: "development"
          ssh_private_key: ${{ secrets.SYNC_TOKEN }}

