
name: Sync Repositories

on:
  push:
    branches:
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Push to destination repository
        env:
          PAT: ${{ secrets.SYNC_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "Sync Bot"
          git config --global user.email "sync-bot@users.noreply.github.com"
          
          # Get all branches and tags
          git fetch --prune --unshallow
          
          # Add destination as remote
          git remote add destination https://$PAT@github.com/vaihainfo/cc--Trace-backend.git
          
          # Push development branch to destination
          git push destination development:development
